title: Ubuntu | Česká republika
description: Ubuntu je operační systém se svobodnou licencí, který nachází uplatnění na osobních počítačích a serverech stejně jako v cloudu a ve světě internetu věcí.
logo: /images/icons/picto-ubuntu.svg
lang: cs
keywords: Ubuntu, free, opensource, software, operační systém, Linux, zdarma, bezplatný, windows, náhrada, svižný, bezpečný, inovace, novinky, aktualizace, obchod, bez virů, herní
author:
    name: Martin Kozub

remote_content:
  - name: 'ubuntublog'
    url: 'https://blog.ubuntu.com/feed/'
  - name: 'ubuntuczblog'
    url: 'http://blog.ubuntu.cz/rss.xml'
  - name: 'omgubuntu'
    url: 'https://feeds.feedburner.com/d0od?format=xml'

# Build settings
markdown: kramdown
include: [
    '/_pages',
]
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - CNAME
  - README.md
  - release.sh
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-tidy
  - jekyll-redirect-from
